wolffste/rent_a_band

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200224153500_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
created User model with devise
=> created user model

app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, config/environments/development.rb, config/environments/production.rb
=> alerts changed

Gemfile, Gemfile.lock, db/seeds.rb
integrated 10 band seeds in model
=> Seeds for local users

app/models/band.rb, db/migrate/20200224180724_add_user_to_bands.rb, db/schema.rb, db/seeds.rb
=> seed for band_2

app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Added three band cards to our homepage
=> Band cards homepage

app/views/pages/home.html.erb
=> button home

app/controllers/bookings_controller.rb, app/models/booking.rb, app/policies/booking_policy.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, config/routes.rb, db/migrate/20200225145609_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb, test/policies/booking_policy_test.rb
bookings controller model and views
=> Bookings controller

app/views/shared/_navbar.html.erb
Added link to create band on homepage navbar
=> added link on homepage

app/views/bands/show.html.erb, app/views/shared/_navbar.html.erb
=> Link to booking

app/views/bands/show.html.erb, app/views/shared/_navbar.html.erb
make the booking form look nicer
=> Bookingnewbeautiful

app/views/bookings/show.html.erb
added details and photo to booking show page
=> bandshowpage

app/views/bands/filter.html.erb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
=> Filterpage

app/assets/stylesheets/pages/_profile.scss, app/views/bands/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
In navbar messages raus und all bands rein
=> Messageraus

app/assets/stylesheets/pages/_profile.scss, app/views/bands/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
zweiter button zu index wieder raus
=> 2ndbuttonraus

app/views/shared/_navbar.html.erb
=> verlinkung logo

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/bands/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
=> Stickyfooter

app/assets/stylesheets/components/_band_card.scss, app/views/bands/index.html.erb
=> index design

app/views/bands/show.html.erb
to dashboard anstatt zu to index
=> link to dashboard

app/views/bands/show.html.erb
button wieder zu back to overview
=> button wieder zurück

app/assets/stylesheets/pages/_profile.scss, app/controllers/bands_controller.rb, app/views/pages/show_dashboard.html.erb
=> Dashboard kram
